// Docker Commands - Popup Script
class DockerCommands {
  constructor() { this.commands = [{cmd:'docker build -t <name> .',desc:'Build image from Dockerfile'},{cmd:'docker run <image>',desc:'Run container from image'},{cmd:'docker run -d <image>',desc:'Run in detached mode'},{cmd:'docker run -p 8080:80 <img>',desc:'Map port 8080 to 80'},{cmd:'docker run -v /host:/cont <img>',desc:'Mount volume'},{cmd:'docker ps',desc:'List running containers'},{cmd:'docker ps -a',desc:'List all containers'},{cmd:'docker images',desc:'List images'},{cmd:'docker stop <container>',desc:'Stop container'},{cmd:'docker start <container>',desc:'Start container'},{cmd:'docker restart <container>',desc:'Restart container'},{cmd:'docker rm <container>',desc:'Remove container'},{cmd:'docker rmi <image>',desc:'Remove image'},{cmd:'docker exec -it <cont> bash',desc:'Shell into container'},{cmd:'docker logs <container>',desc:'View container logs'},{cmd:'docker logs -f <container>',desc:'Follow logs'},{cmd:'docker pull <image>',desc:'Pull image from registry'},{cmd:'docker push <image>',desc:'Push to registry'},{cmd:'docker-compose up',desc:'Start compose services'},{cmd:'docker-compose up -d',desc:'Start in background'},{cmd:'docker-compose down',desc:'Stop and remove'},{cmd:'docker system prune',desc:'Clean up unused resources'}]; this.initElements(); this.bindEvents(); this.render(); }
  initElements() { this.search = document.getElementById('search'); this.list = document.getElementById('cmdList'); }
  bindEvents() { this.search.addEventListener('input', () => this.render()); }
  render() { const q = this.search.value.toLowerCase(); const filtered = this.commands.filter(c => c.cmd.toLowerCase().includes(q) || c.desc.toLowerCase().includes(q)); this.list.innerHTML = filtered.map(c => `<div class="cmd-item" onclick="navigator.clipboard.writeText('${c.cmd.replace(/'/g,"\\'")}')"><div class="cmd-name">${this.escapeHtml(c.cmd)}</div><div class="cmd-desc">${c.desc}</div></div>`).join(''); }
  escapeHtml(s) { return s.replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
}
document.addEventListener('DOMContentLoaded', () => new DockerCommands());
