// YAML Formatter - Popup Script
class YamlFormatter {
  constructor() { this.initElements(); this.bindEvents(); }
  initElements() { this.inputEl = document.getElementById('yamlInput'); this.outputEl = document.getElementById('yamlOutput'); this.statusEl = document.getElementById('status'); this.formatBtn = document.getElementById('formatBtn'); this.validateBtn = document.getElementById('validateBtn'); this.copyBtn = document.getElementById('copyBtn'); }
  bindEvents() { this.formatBtn.addEventListener('click', () => this.format()); this.validateBtn.addEventListener('click', () => this.validate()); this.copyBtn.addEventListener('click', () => this.copy()); }
  parseYaml(text) { const lines = text.split('\n'); const result = []; let currentIndent = 0; for (let line of lines) { const trimmed = line.trim(); if (!trimmed || trimmed.startsWith('#')) continue; const indent = line.search(/\S/); const isListItem = trimmed.startsWith('- '); const colonIdx = trimmed.indexOf(':'); if (colonIdx > 0) { const key = trimmed.substring(isListItem ? 2 : 0, colonIdx).trim(); const value = trimmed.substring(colonIdx + 1).trim(); result.push({ indent, key, value, isListItem }); } else if (isListItem) { result.push({ indent, value: trimmed.substring(2), isListItem: true }); } } return result; }
  format() { let yaml = this.inputEl.value.trim(); if (!yaml) return; try { const lines = yaml.split('\n'); const formatted = []; for (let line of lines) { const trimmed = line.trim(); if (!trimmed) { formatted.push(''); continue; } if (trimmed.startsWith('#')) { formatted.push(line); continue; } const indent = line.search(/\S/); const spaces = '  '.repeat(Math.floor(indent / 2)); formatted.push(spaces + trimmed); } this.outputEl.value = formatted.join('\n'); this.showStatus('Formatted successfully', true); } catch (e) { this.showStatus('Format error: ' + e.message, false); } }
  validate() { const yaml = this.inputEl.value.trim(); if (!yaml) { this.showStatus('Please enter YAML', false); return; } try { const lines = yaml.split('\n'); let errors = []; let prevIndent = 0; for (let i = 0; i < lines.length; i++) { const line = lines[i]; const trimmed = line.trim(); if (!trimmed || trimmed.startsWith('#')) continue; const indent = line.search(/\S/); if (indent % 2 !== 0) errors.push(`Line ${i+1}: Odd indentation`); if (indent > prevIndent + 2) errors.push(`Line ${i+1}: Excessive indentation`); if (!trimmed.startsWith('-') && !trimmed.includes(':') && prevIndent >= indent) errors.push(`Line ${i+1}: Missing key-value separator`); prevIndent = indent; } if (errors.length === 0) { this.showStatus('Valid YAML structure', true); this.outputEl.value = yaml; } else { this.showStatus(errors[0], false); this.outputEl.value = errors.join('\n'); } } catch (e) { this.showStatus('Validation error: ' + e.message, false); } }
  showStatus(msg, valid) { this.statusEl.textContent = msg; this.statusEl.className = 'status ' + (valid ? 'valid' : 'invalid'); }
  async copy() { if (!this.outputEl.value) return; await navigator.clipboard.writeText(this.outputEl.value); this.copyBtn.textContent = 'Copied!'; setTimeout(() => { this.copyBtn.textContent = 'Copy'; }, 1500); }
}
document.addEventListener('DOMContentLoaded', () => new YamlFormatter());
