// JSON Schema Validator - Popup Script
class SchemaValidator {
  constructor() { this.initElements(); this.bindEvents(); }
  initElements() { this.jsonInput = document.getElementById('jsonInput'); this.schemaInput = document.getElementById('schemaInput'); this.validateBtn = document.getElementById('validateBtn'); this.result = document.getElementById('result'); }
  bindEvents() { this.validateBtn.addEventListener('click', () => this.validate()); }
  validate() { const jsonStr = this.jsonInput.value.trim(); const schemaStr = this.schemaInput.value.trim(); if (!jsonStr || !schemaStr) { this.showResult('Please enter both JSON and schema', 'empty'); return; } let data, schema; try { data = JSON.parse(jsonStr); } catch (e) { this.showResult('Invalid JSON: ' + e.message, 'invalid'); return; } try { schema = JSON.parse(schemaStr); } catch (e) { this.showResult('Invalid schema: ' + e.message, 'invalid'); return; } const errors = this.validateAgainstSchema(data, schema, ''); if (errors.length === 0) { this.showResult('✓ Valid! JSON matches the schema.', 'valid'); } else { this.showResult('✗ Invalid:\n' + errors.join('\n'), 'invalid'); } }
  validateAgainstSchema(data, schema, path) { const errors = []; const type = schema.type; if (type) { const actualType = Array.isArray(data) ? 'array' : typeof data; if (type !== actualType && !(type === 'integer' && typeof data === 'number' && Number.isInteger(data))) { errors.push(`${path || 'root'}: Expected ${type}, got ${actualType}`); return errors; } } if (schema.properties && typeof data === 'object' && !Array.isArray(data)) { for (const key of Object.keys(schema.properties)) { if (data.hasOwnProperty(key)) { errors.push(...this.validateAgainstSchema(data[key], schema.properties[key], `${path}.${key}`)); } } } if (schema.required && Array.isArray(schema.required)) { for (const key of schema.required) { if (!data.hasOwnProperty(key)) { errors.push(`${path || 'root'}: Missing required property "${key}"`); } } } if (schema.items && Array.isArray(data)) { data.forEach((item, i) => { errors.push(...this.validateAgainstSchema(item, schema.items, `${path}[${i}]`)); }); } if (schema.minimum !== undefined && typeof data === 'number' && data < schema.minimum) { errors.push(`${path}: Value ${data} is less than minimum ${schema.minimum}`); } if (schema.maximum !== undefined && typeof data === 'number' && data > schema.maximum) { errors.push(`${path}: Value ${data} exceeds maximum ${schema.maximum}`); } return errors; }
  showResult(msg, type) { this.result.textContent = msg; this.result.className = 'result ' + type; }
}
document.addEventListener('DOMContentLoaded', () => new SchemaValidator());
