// Partnership Proposal - Popup Script
class PartnershipProposal {
  constructor() { this.proposals = []; this.initElements(); this.bindEvents(); this.loadData(); }
  initElements() { this.typeEl = document.getElementById('partnerType'); this.partnerEl = document.getElementById('partner'); this.companyEl = document.getElementById('company'); this.opportunityEl = document.getElementById('opportunity'); this.benefitsEl = document.getElementById('benefits'); this.copyBtn = document.getElementById('copyProposal'); this.saveBtn = document.getElementById('saveProposal'); this.listEl = document.getElementById('proposalList'); }
  bindEvents() { this.copyBtn.addEventListener('click', () => this.copyProposal()); this.saveBtn.addEventListener('click', () => this.saveProposal()); }
  async loadData() { const r = await chrome.storage.local.get('partnershipProposals'); if (r.partnershipProposals) this.proposals = r.partnershipProposals; this.render(); }
  async saveData() { await chrome.storage.local.set({ partnershipProposals: this.proposals }); }
  getTypeLabel(t) { const l = { strategic: 'Strategic', affiliate: 'Affiliate', integration: 'Integration', reseller: 'Reseller', comarketing: 'Co-Marketing' }; return l[t] || t; }
  formatProposal() { const p = this.partnerEl.value.trim(); const c = this.companyEl.value.trim(); const o = this.opportunityEl.value.trim(); const b = this.benefitsEl.value.trim(); let prop = `Dear${p ? ` ${p}` : ''},\n\nI am reaching out from ${c || 'our company'} to explore a potential partnership.\n\n`; if (o) prop += `Opportunity:\n${o}\n\n`; if (b) prop += `Mutual Benefits:\n${b}\n\n`; prop += 'I believe together we can create significant value. Would you be open to a brief call to discuss?\n\nBest regards'; return prop; }
  async copyProposal() { await navigator.clipboard.writeText(this.formatProposal()); const o = this.copyBtn.textContent; this.copyBtn.textContent = 'Copied!'; setTimeout(() => { this.copyBtn.textContent = o; }, 1500); }
  saveProposal() { const p = this.partnerEl.value.trim(); if (!p) return; this.proposals.unshift({ id: Date.now(), type: this.typeEl.value, partner: p, company: this.companyEl.value.trim(), opportunity: this.opportunityEl.value.trim(), benefits: this.benefitsEl.value.trim(), created: Date.now() }); if (this.proposals.length > 15) this.proposals.pop(); this.saveData(); this.render(); const o = this.saveBtn.textContent; this.saveBtn.textContent = 'Saved!'; setTimeout(() => { this.saveBtn.textContent = o; }, 1500); }
  loadProposal(id) { const p = this.proposals.find(p => p.id === id); if (p) { this.typeEl.value = p.type || 'strategic'; this.partnerEl.value = p.partner || ''; this.companyEl.value = p.company || ''; this.opportunityEl.value = p.opportunity || ''; this.benefitsEl.value = p.benefits || ''; } }
  deleteProposal(id) { this.proposals = this.proposals.filter(p => p.id !== id); this.saveData(); this.render(); }
  escapeHtml(t) { const d = document.createElement('div'); d.textContent = t; return d.innerHTML; }
  truncate(t, l = 25) { return (!t || t.length <= l) ? (t || '') : t.substring(0, l) + '...'; }
  render() { if (this.proposals.length === 0) { this.listEl.innerHTML = '<div class="empty-state">No saved proposals</div>'; return; } this.listEl.innerHTML = this.proposals.map(p => `<div class="proposal-item"><div class="proposal-info"><div class="proposal-partner">${this.escapeHtml(this.truncate(p.partner))}</div><div class="proposal-type">${this.getTypeLabel(p.type)}</div></div><div class="proposal-actions"><button class="load-btn" data-load="${p.id}">Load</button><button class="delete-btn" data-delete="${p.id}">Del</button></div></div>`).join(''); this.listEl.querySelectorAll('[data-load]').forEach(b => b.addEventListener('click', () => this.loadProposal(parseInt(b.dataset.load)))); this.listEl.querySelectorAll('[data-delete]').forEach(b => b.addEventListener('click', () => this.deleteProposal(parseInt(b.dataset.delete)))); }
}
document.addEventListener('DOMContentLoaded', () => new PartnershipProposal());
