// Mock Data Generator - Popup Script
class MockDataGenerator {
  constructor() { this.firstNames = ['James','Mary','John','Patricia','Robert','Jennifer','Michael','Linda','William','Elizabeth','David','Barbara','Richard','Susan','Joseph','Jessica','Thomas','Sarah','Charles','Karen']; this.lastNames = ['Smith','Johnson','Williams','Brown','Jones','Garcia','Miller','Davis','Rodriguez','Martinez','Hernandez','Lopez','Gonzalez','Wilson','Anderson','Thomas','Taylor','Moore','Jackson','Martin']; this.streets = ['Main St','Oak Ave','Maple Dr','Cedar Ln','Pine Rd','Elm St','Park Ave','Washington Blvd','Lake Dr','River Rd']; this.cities = ['New York','Los Angeles','Chicago','Houston','Phoenix','Philadelphia','San Antonio','San Diego','Dallas','San Jose']; this.products = ['Laptop','Phone','Tablet','Headphones','Camera','Watch','Speaker','Monitor','Keyboard','Mouse']; this.domains = ['gmail.com','yahoo.com','outlook.com','hotmail.com','example.com']; this.initElements(); this.bindEvents(); }
  initElements() { this.dataType = document.getElementById('dataType'); this.count = document.getElementById('count'); this.output = document.getElementById('output'); this.generateBtn = document.getElementById('generateBtn'); this.copyBtn = document.getElementById('copyBtn'); }
  bindEvents() { this.generateBtn.addEventListener('click', () => this.generate()); this.copyBtn.addEventListener('click', () => this.copy()); }
  random(arr) { return arr[Math.floor(Math.random() * arr.length)]; }
  randomNum(min, max) { return Math.floor(Math.random() * (max - min + 1)) + min; }
  uuid() { return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => { const r = Math.random() * 16 | 0; return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16); }); }
  generateItem(type) { switch(type) { case 'user': return { id: this.uuid(), firstName: this.random(this.firstNames), lastName: this.random(this.lastNames), email: `${this.random(this.firstNames).toLowerCase()}${this.randomNum(1,999)}@${this.random(this.domains)}`, age: this.randomNum(18, 65) }; case 'address': return { street: `${this.randomNum(100,9999)} ${this.random(this.streets)}`, city: this.random(this.cities), zip: String(this.randomNum(10000, 99999)), country: 'USA' }; case 'product': return { id: this.uuid(), name: this.random(this.products), price: parseFloat((Math.random() * 1000).toFixed(2)), stock: this.randomNum(0, 500) }; case 'email': return `${this.random(this.firstNames).toLowerCase()}${this.randomNum(1,999)}@${this.random(this.domains)}`; case 'phone': return `+1-${this.randomNum(200,999)}-${this.randomNum(200,999)}-${this.randomNum(1000,9999)}`; case 'uuid': return this.uuid(); default: return {}; } }
  generate() { const type = this.dataType.value; const n = Math.min(parseInt(this.count.value) || 5, 50); const data = Array.from({ length: n }, () => this.generateItem(type)); this.output.value = JSON.stringify(data, null, 2); }
  async copy() { if (!this.output.value) return; await navigator.clipboard.writeText(this.output.value); this.copyBtn.textContent = 'Copied!'; setTimeout(() => { this.copyBtn.textContent = 'Copy JSON'; }, 1500); }
}
document.addEventListener('DOMContentLoaded', () => new MockDataGenerator());
