// Linux Commands - Popup Script
class LinuxCommands {
  constructor() { this.commands = [{cmd:'ls',desc:'List directory contents',cat:'file'},{cmd:'ls -la',desc:'List with details',cat:'file'},{cmd:'cd <dir>',desc:'Change directory',cat:'file'},{cmd:'pwd',desc:'Print working directory',cat:'file'},{cmd:'mkdir <dir>',desc:'Create directory',cat:'file'},{cmd:'rm <file>',desc:'Remove file',cat:'file'},{cmd:'rm -rf <dir>',desc:'Remove directory recursively',cat:'file'},{cmd:'cp <src> <dst>',desc:'Copy file',cat:'file'},{cmd:'mv <src> <dst>',desc:'Move/rename file',cat:'file'},{cmd:'cat <file>',desc:'Display file contents',cat:'file'},{cmd:'head -n 10 <file>',desc:'First 10 lines',cat:'file'},{cmd:'tail -n 10 <file>',desc:'Last 10 lines',cat:'file'},{cmd:'tail -f <file>',desc:'Follow file changes',cat:'file'},{cmd:'grep <pattern> <file>',desc:'Search in file',cat:'file'},{cmd:'find . -name "<pattern>"',desc:'Find files',cat:'file'},{cmd:'chmod 755 <file>',desc:'Change permissions',cat:'file'},{cmd:'chown user:group <file>',desc:'Change ownership',cat:'file'},{cmd:'ps aux',desc:'List all processes',cat:'sys'},{cmd:'top',desc:'System monitor',cat:'sys'},{cmd:'htop',desc:'Interactive monitor',cat:'sys'},{cmd:'kill <pid>',desc:'Kill process',cat:'sys'},{cmd:'killall <name>',desc:'Kill by name',cat:'sys'},{cmd:'df -h',desc:'Disk space usage',cat:'sys'},{cmd:'du -sh <dir>',desc:'Directory size',cat:'sys'},{cmd:'free -h',desc:'Memory usage',cat:'sys'},{cmd:'uname -a',desc:'System info',cat:'sys'},{cmd:'whoami',desc:'Current user',cat:'sys'},{cmd:'sudo <cmd>',desc:'Run as root',cat:'sys'},{cmd:'systemctl status <svc>',desc:'Service status',cat:'sys'},{cmd:'journalctl -u <svc>',desc:'Service logs',cat:'sys'},{cmd:'ping <host>',desc:'Ping host',cat:'net'},{cmd:'curl <url>',desc:'HTTP request',cat:'net'},{cmd:'wget <url>',desc:'Download file',cat:'net'},{cmd:'ssh user@host',desc:'SSH connect',cat:'net'},{cmd:'scp <src> user@host:<dst>',desc:'Secure copy',cat:'net'},{cmd:'netstat -tulpn',desc:'Network connections',cat:'net'},{cmd:'ss -tulpn',desc:'Socket stats',cat:'net'},{cmd:'ifconfig',desc:'Network interfaces',cat:'net'},{cmd:'ip addr',desc:'IP addresses',cat:'net'}]; this.cat = 'all'; this.initElements(); this.bindEvents(); this.render(); }
  initElements() { this.search = document.getElementById('search'); this.list = document.getElementById('cmdList'); this.tabs = document.querySelectorAll('.tab'); }
  bindEvents() { this.search.addEventListener('input', () => this.render()); this.tabs.forEach(t => t.addEventListener('click', () => { this.tabs.forEach(x => x.classList.remove('active')); t.classList.add('active'); this.cat = t.dataset.cat; this.render(); })); }
  render() { const q = this.search.value.toLowerCase(); const filtered = this.commands.filter(c => (this.cat === 'all' || c.cat === this.cat) && (c.cmd.toLowerCase().includes(q) || c.desc.toLowerCase().includes(q))); this.list.innerHTML = filtered.map(c => `<div class="cmd-item" onclick="navigator.clipboard.writeText('${c.cmd.replace(/'/g,"\\'")}')"><div class="cmd-name">${this.escapeHtml(c.cmd)}</div><div class="cmd-desc">${c.desc}</div></div>`).join(''); }
  escapeHtml(s) { return s.replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
}
document.addEventListener('DOMContentLoaded', () => new LinuxCommands());
