// CSS Templates - Popup Script
class CSSTemplates {
  constructor() { this.templates = [{name:'Reset',code:'* {\n  margin: 0;\n  padding: 0;\n  box-sizing: border-box;\n}'},{name:'Body Base',code:'body {\n  font-family: system-ui, sans-serif;\n  line-height: 1.5;\n  color: #333;\n  background: #fff;\n}'},{name:'Container',code:'.container {\n  max-width: 1200px;\n  margin: 0 auto;\n  padding: 0 20px;\n}'},{name:'Flexbox Center',code:'.flex-center {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n}'},{name:'Flexbox Space Between',code:'.flex-between {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n}'},{name:'Grid 3 Columns',code:'.grid-3 {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 20px;\n}'},{name:'Button',code:'.btn {\n  display: inline-block;\n  padding: 10px 20px;\n  border: none;\n  border-radius: 4px;\n  background: #3b82f6;\n  color: white;\n  cursor: pointer;\n}\n.btn:hover {\n  background: #2563eb;\n}'},{name:'Card',code:'.card {\n  background: white;\n  border-radius: 8px;\n  box-shadow: 0 2px 8px rgba(0,0,0,0.1);\n  padding: 20px;\n}'},{name:'Input',code:'input {\n  width: 100%;\n  padding: 10px 12px;\n  border: 1px solid #ddd;\n  border-radius: 4px;\n  font-size: 16px;\n}\ninput:focus {\n  outline: none;\n  border-color: #3b82f6;\n}'},{name:'Truncate Text',code:'.truncate {\n  white-space: nowrap;\n  overflow: hidden;\n  text-overflow: ellipsis;\n}'},{name:'Visually Hidden',code:'.sr-only {\n  position: absolute;\n  width: 1px;\n  height: 1px;\n  padding: 0;\n  margin: -1px;\n  overflow: hidden;\n  clip: rect(0,0,0,0);\n  border: 0;\n}'},{name:'Responsive Image',code:'img {\n  max-width: 100%;\n  height: auto;\n  display: block;\n}'},{name:'CSS Variables',code:':root {\n  --primary: #3b82f6;\n  --secondary: #64748b;\n  --text: #1e293b;\n  --bg: #f8fafc;\n}'},{name:'Media Query',code:'@media (max-width: 768px) {\n  .container {\n    padding: 0 15px;\n  }\n}'}]; this.initElements(); this.bindEvents(); this.render(); }
  initElements() { this.search = document.getElementById('search'); this.list = document.getElementById('templateList'); }
  bindEvents() { this.search.addEventListener('input', () => this.render()); }
  render() { const q = this.search.value.toLowerCase(); const filtered = this.templates.filter(t => t.name.toLowerCase().includes(q) || t.code.toLowerCase().includes(q)); this.list.innerHTML = filtered.map(t => `<div class="template-item" onclick="navigator.clipboard.writeText(\`${t.code.replace(/`/g,'\\`')}\`)"><div class="template-name">${t.name}</div><div class="template-code">${this.escapeHtml(t.code)}</div></div>`).join(''); }
  escapeHtml(s) { return s.replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
}
document.addEventListener('DOMContentLoaded', () => new CSSTemplates());
