// C# Snippets - Popup Script
class CSharpSnippets {
  constructor() { this.snippets = [{name:'Hello World',code:'Console.WriteLine("Hello, World!");'},{name:'Variables',code:'string name = "C#";\nint age = 25;\nbool active = true;'},{name:'Method',code:'public string Greet(string name)\n{\n    return $"Hello, {name}";\n}'},{name:'Class',code:'public class User\n{\n    public string Name { get; set; }\n    public int Age { get; set; }\n    \n    public User(string name, int age)\n    {\n        Name = name;\n        Age = age;\n    }\n}'},{name:'Property',code:'public string Name { get; set; }\npublic int Age { get; private set; }'},{name:'Interface',code:'public interface IGreetable\n{\n    string Greet();\n}'},{name:'Async Method',code:'public async Task<string> FetchDataAsync()\n{\n    var result = await httpClient.GetAsync(url);\n    return await result.Content.ReadAsStringAsync();\n}'},{name:'If-Else',code:'if (x > 0)\n{\n    Console.WriteLine("positive");\n}\nelse if (x < 0)\n{\n    Console.WriteLine("negative");\n}\nelse\n{\n    Console.WriteLine("zero");\n}'},{name:'Switch',code:'switch (value)\n{\n    case "a":\n        Console.WriteLine("A");\n        break;\n    case "b":\n        Console.WriteLine("B");\n        break;\n    default:\n        Console.WriteLine("Other");\n        break;\n}'},{name:'For Loop',code:'for (int i = 0; i < 10; i++)\n{\n    Console.WriteLine(i);\n}'},{name:'Foreach',code:'foreach (var item in items)\n{\n    Console.WriteLine(item);\n}'},{name:'List',code:'var list = new List<int> { 1, 2, 3 };\nlist.Add(4);'},{name:'Dictionary',code:'var dict = new Dictionary<string, int>\n{\n    { "key", 42 }\n};\ndict["new"] = 100;'},{name:'LINQ',code:'var evens = numbers.Where(n => n % 2 == 0);\nvar doubled = numbers.Select(n => n * 2);'},{name:'Try-Catch',code:'try\n{\n    // Code\n}\ncatch (Exception ex)\n{\n    Console.WriteLine(ex.Message);\n}'},{name:'Null Coalescing',code:'var value = nullableValue ?? defaultValue;\nname?.ToUpper();'}]; this.initElements(); this.bindEvents(); this.render(); }
  initElements() { this.search = document.getElementById('search'); this.list = document.getElementById('snippetList'); }
  bindEvents() { this.search.addEventListener('input', () => this.render()); }
  render() { const q = this.search.value.toLowerCase(); const filtered = this.snippets.filter(s => s.name.toLowerCase().includes(q) || s.code.toLowerCase().includes(q)); this.list.innerHTML = filtered.map(s => `<div class="snippet-item" onclick="navigator.clipboard.writeText(\`${s.code.replace(/`/g,'\\`').replace(/\\/g,'\\\\')}\`)"><div class="snippet-name">${s.name}</div><div class="snippet-code">${this.escapeHtml(s.code)}</div></div>`).join(''); }
  escapeHtml(s) { return s.replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
}
document.addEventListener('DOMContentLoaded', () => new CSharpSnippets());
