// Wrap-up Summary - Popup Script
class WrapupSummary {
  constructor() { this.summaries = []; this.initElements(); this.bindEvents(); this.loadData(); }
  initElements() { this.typeEl = document.getElementById('summaryType'); this.titleEl = document.getElementById('title'); this.achievementsEl = document.getElementById('achievements'); this.lessonsEl = document.getElementById('lessons'); this.nextEl = document.getElementById('nextActions'); this.copyBtn = document.getElementById('copySummary'); this.saveBtn = document.getElementById('saveSummary'); this.listEl = document.getElementById('summaryList'); }
  bindEvents() { this.copyBtn.addEventListener('click', () => this.copySummary()); this.saveBtn.addEventListener('click', () => this.saveSummary()); }
  async loadData() { const r = await chrome.storage.local.get('wrapupSummaries'); if (r.wrapupSummaries) this.summaries = r.wrapupSummaries; this.render(); }
  async saveData() { await chrome.storage.local.set({ wrapupSummaries: this.summaries }); }
  getTypeLabel(t) { const l = { project: 'Project Completion', meeting: 'Meeting Recap', sprint: 'Sprint Summary', quarter: 'Quarterly Review', year: 'Annual Review' }; return l[t] || t; }
  formatSummary() { const t = this.titleEl.value.trim(); const a = this.achievementsEl.value.trim(); const les = this.lessonsEl.value.trim(); const n = this.nextEl.value.trim(); let s = `${this.getTypeLabel(this.typeEl.value).toUpperCase()}\n${'='.repeat(30)}\n\n`; if (t) s += `Title: ${t}\n\n`; if (a) s += `KEY ACHIEVEMENTS:\n${a}\n\n`; if (les) s += `LESSONS LEARNED:\n${les}\n\n`; if (n) s += `RECOMMENDED NEXT ACTIONS:\n${n}\n\n`; s += `Date: ${new Date().toLocaleDateString()}\n\nThank you for your contributions!`; return s; }
  async copySummary() { await navigator.clipboard.writeText(this.formatSummary()); const o = this.copyBtn.textContent; this.copyBtn.textContent = 'Copied!'; setTimeout(() => { this.copyBtn.textContent = o; }, 1500); }
  saveSummary() { const t = this.titleEl.value.trim(); if (!t) return; this.summaries.unshift({ id: Date.now(), type: this.typeEl.value, title: t, achievements: this.achievementsEl.value.trim(), lessons: this.lessonsEl.value.trim(), nextActions: this.nextEl.value.trim(), created: Date.now() }); if (this.summaries.length > 15) this.summaries.pop(); this.saveData(); this.render(); const o = this.saveBtn.textContent; this.saveBtn.textContent = 'Saved!'; setTimeout(() => { this.saveBtn.textContent = o; }, 1500); }
  loadSummary(id) { const s = this.summaries.find(s => s.id === id); if (s) { this.typeEl.value = s.type || 'project'; this.titleEl.value = s.title || ''; this.achievementsEl.value = s.achievements || ''; this.lessonsEl.value = s.lessons || ''; this.nextEl.value = s.nextActions || ''; } }
  deleteSummary(id) { this.summaries = this.summaries.filter(s => s.id !== id); this.saveData(); this.render(); }
  escapeHtml(t) { const d = document.createElement('div'); d.textContent = t; return d.innerHTML; }
  truncate(t, l = 25) { return (!t || t.length <= l) ? (t || '') : t.substring(0, l) + '...'; }
  render() { if (this.summaries.length === 0) { this.listEl.innerHTML = '<div class="empty-state">No saved summaries</div>'; return; } this.listEl.innerHTML = this.summaries.map(s => `<div class="summary-item"><div class="summary-info"><div class="summary-title">${this.escapeHtml(this.truncate(s.title))}</div><div class="summary-type">${this.escapeHtml(s.type)}</div></div><div class="summary-actions"><button class="load-btn" data-load="${s.id}">Load</button><button class="delete-btn" data-delete="${s.id}">Del</button></div></div>`).join(''); this.listEl.querySelectorAll('[data-load]').forEach(b => b.addEventListener('click', () => this.loadSummary(parseInt(b.dataset.load)))); this.listEl.querySelectorAll('[data-delete]').forEach(b => b.addEventListener('click', () => this.deleteSummary(parseInt(b.dataset.delete)))); }
}
document.addEventListener('DOMContentLoaded', () => new WrapupSummary());
