// Go Snippets - Popup Script
class GoSnippets {
  constructor() { this.snippets = [{name:'Hello World',code:'package main\n\nimport "fmt"\n\nfunc main() {\n    fmt.Println("Hello, World!")\n}'},{name:'Variables',code:'var name string = "Go"\nage := 25\nconst Pi = 3.14'},{name:'Function',code:'func add(a, b int) int {\n    return a + b\n}'},{name:'Multiple Returns',code:'func divide(a, b float64) (float64, error) {\n    if b == 0 {\n        return 0, errors.New("divide by zero")\n    }\n    return a / b, nil\n}'},{name:'Struct',code:'type User struct {\n    ID   int\n    Name string\n    Age  int\n}'},{name:'Method',code:'func (u *User) Greet() string {\n    return "Hello, " + u.Name\n}'},{name:'Interface',code:'type Reader interface {\n    Read(p []byte) (n int, err error)\n}'},{name:'Slice',code:'nums := []int{1, 2, 3}\nnums = append(nums, 4)\nfmt.Println(len(nums))'},{name:'Map',code:'m := make(map[string]int)\nm["key"] = 42\nval, ok := m["key"]'},{name:'For Loop',code:'for i := 0; i < 10; i++ {\n    fmt.Println(i)\n}'},{name:'For Range',code:'for i, v := range slice {\n    fmt.Println(i, v)\n}'},{name:'If-Else',code:'if x > 0 {\n    fmt.Println("positive")\n} else if x < 0 {\n    fmt.Println("negative")\n} else {\n    fmt.Println("zero")\n}'},{name:'Switch',code:'switch day {\ncase "Mon":\n    fmt.Println("Monday")\ncase "Tue":\n    fmt.Println("Tuesday")\ndefault:\n    fmt.Println("Other")\n}'},{name:'Error Handling',code:'result, err := doSomething()\nif err != nil {\n    log.Fatal(err)\n}'},{name:'Goroutine',code:'go func() {\n    // Concurrent code\n}()'},{name:'Channel',code:'ch := make(chan int)\ngo func() { ch <- 42 }()\nval := <-ch'},{name:'Defer',code:'func readFile() {\n    f, _ := os.Open("file.txt")\n    defer f.Close()\n    // Use file\n}'},{name:'HTTP Handler',code:'func handler(w http.ResponseWriter, r *http.Request) {\n    fmt.Fprintf(w, "Hello!")\n}\nhttp.HandleFunc("/", handler)'}]; this.initElements(); this.bindEvents(); this.render(); }
  initElements() { this.search = document.getElementById('search'); this.list = document.getElementById('snippetList'); }
  bindEvents() { this.search.addEventListener('input', () => this.render()); }
  render() { const q = this.search.value.toLowerCase(); const filtered = this.snippets.filter(s => s.name.toLowerCase().includes(q) || s.code.toLowerCase().includes(q)); this.list.innerHTML = filtered.map(s => `<div class="snippet-item" onclick="navigator.clipboard.writeText(\`${s.code.replace(/`/g,'\\`').replace(/\\/g,'\\\\')}\`)"><div class="snippet-name">${s.name}</div><div class="snippet-code">${this.escapeHtml(s.code)}</div></div>`).join(''); }
  escapeHtml(s) { return s.replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
}
document.addEventListener('DOMContentLoaded', () => new GoSnippets());
