// Rust Snippets - Popup Script
class RustSnippets {
  constructor() { this.snippets = [{name:'Hello World',code:'fn main() {\n    println!("Hello, World!");\n}'},{name:'Variables',code:'let x = 5;\nlet mut y = 10;\nconst MAX: u32 = 100;'},{name:'Function',code:'fn add(a: i32, b: i32) -> i32 {\n    a + b\n}'},{name:'Struct',code:'struct User {\n    name: String,\n    age: u32,\n    active: bool,\n}'},{name:'Impl',code:'impl User {\n    fn new(name: String) -> Self {\n        Self { name, age: 0, active: true }\n    }\n    \n    fn greet(&self) -> String {\n        format!("Hello, {}", self.name)\n    }\n}'},{name:'Enum',code:'enum Status {\n    Active,\n    Inactive,\n    Pending(String),\n}'},{name:'Match',code:'match status {\n    Status::Active => println!("Active"),\n    Status::Pending(msg) => println!("{}", msg),\n    _ => println!("Other"),\n}'},{name:'Option',code:'let opt: Option<i32> = Some(42);\nif let Some(val) = opt {\n    println!("{}", val);\n}'},{name:'Result',code:'fn divide(a: f64, b: f64) -> Result<f64, String> {\n    if b == 0.0 {\n        Err("Division by zero".to_string())\n    } else {\n        Ok(a / b)\n    }\n}'},{name:'Error Handling',code:'let result = do_something()?;\n\nmatch result {\n    Ok(val) => println!("{}", val),\n    Err(e) => eprintln!("Error: {}", e),\n}'},{name:'Vector',code:'let mut vec = vec![1, 2, 3];\nvec.push(4);\nfor item in &vec {\n    println!("{}", item);\n}'},{name:'HashMap',code:'use std::collections::HashMap;\n\nlet mut map = HashMap::new();\nmap.insert("key", 42);\nif let Some(val) = map.get("key") {\n    println!("{}", val);\n}'},{name:'For Loop',code:'for i in 0..10 {\n    println!("{}", i);\n}\n\nfor (i, val) in vec.iter().enumerate() {\n    println!("{}: {}", i, val);\n}'},{name:'Trait',code:'trait Greet {\n    fn greet(&self) -> String;\n}\n\nimpl Greet for User {\n    fn greet(&self) -> String {\n        format!("Hello, {}", self.name)\n    }\n}'},{name:'Generic',code:'fn largest<T: PartialOrd>(list: &[T]) -> &T {\n    let mut largest = &list[0];\n    for item in list {\n        if item > largest {\n            largest = item;\n        }\n    }\n    largest\n}'},{name:'Closure',code:'let add = |a, b| a + b;\nlet result = add(2, 3);'}]; this.initElements(); this.bindEvents(); this.render(); }
  initElements() { this.search = document.getElementById('search'); this.list = document.getElementById('snippetList'); }
  bindEvents() { this.search.addEventListener('input', () => this.render()); }
  render() { const q = this.search.value.toLowerCase(); const filtered = this.snippets.filter(s => s.name.toLowerCase().includes(q) || s.code.toLowerCase().includes(q)); this.list.innerHTML = filtered.map(s => `<div class="snippet-item" onclick="navigator.clipboard.writeText(\`${s.code.replace(/`/g,'\\`').replace(/\\/g,'\\\\')}\`)"><div class="snippet-name">${s.name}</div><div class="snippet-code">${this.escapeHtml(s.code)}</div></div>`).join(''); }
  escapeHtml(s) { return s.replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
}
document.addEventListener('DOMContentLoaded', () => new RustSnippets());
