// Unix Permissions - Popup Script
class UnixPermissions {
  constructor() { this.initElements(); this.bindEvents(); this.update(); }
  initElements() { this.checkboxes = document.querySelectorAll('input[type="checkbox"]'); this.numericResult = document.getElementById('numericResult'); this.symbolicResult = document.getElementById('symbolicResult'); this.commandResult = document.getElementById('commandResult'); this.numericInput = document.getElementById('numericInput'); this.applyBtn = document.getElementById('applyBtn'); this.copyBtn = document.getElementById('copyBtn'); }
  bindEvents() { this.checkboxes.forEach(cb => cb.addEventListener('change', () => this.update())); this.applyBtn.addEventListener('click', () => this.apply()); this.copyBtn.addEventListener('click', () => this.copy()); this.numericInput.addEventListener('keypress', (e) => { if (e.key === 'Enter') this.apply(); }); }
  getNumeric() { const groups = { owner: 0, group: 0, others: 0 }; this.checkboxes.forEach(cb => { if (cb.checked) groups[cb.dataset.group] += parseInt(cb.dataset.perm); }); return `${groups.owner}${groups.group}${groups.others}`; }
  getSymbolic() { const perms = { owner: '', group: '', others: '' }; ['owner', 'group', 'others'].forEach(group => { const cbs = document.querySelectorAll(`input[data-group="${group}"]`); cbs.forEach(cb => { const p = parseInt(cb.dataset.perm); if (p === 4) perms[group] += cb.checked ? 'r' : '-'; if (p === 2) perms[group] += cb.checked ? 'w' : '-'; if (p === 1) perms[group] += cb.checked ? 'x' : '-'; }); }); return perms.owner + perms.group + perms.others; }
  update() { const num = this.getNumeric(); const sym = this.getSymbolic(); this.numericResult.textContent = num; this.symbolicResult.textContent = sym; this.commandResult.textContent = `chmod ${num} file`; }
  apply() { const val = this.numericInput.value.trim(); if (!/^[0-7]{3}$/.test(val)) return; const digits = val.split('').map(Number); const groups = ['owner', 'group', 'others']; groups.forEach((group, i) => { const digit = digits[i]; document.querySelector(`input[data-group="${group}"][data-perm="4"]`).checked = !!(digit & 4); document.querySelector(`input[data-group="${group}"][data-perm="2"]`).checked = !!(digit & 2); document.querySelector(`input[data-group="${group}"][data-perm="1"]`).checked = !!(digit & 1); }); this.update(); }
  async copy() { await navigator.clipboard.writeText(this.commandResult.textContent); this.copyBtn.textContent = 'Copied!'; setTimeout(() => { this.copyBtn.textContent = 'Copy Command'; }, 1500); }
}
document.addEventListener('DOMContentLoaded', () => new UnixPermissions());
