// Git Commands - Popup Script
class GitCommands {
  constructor() { this.commands = [{cmd:'git init',desc:'Initialize new repository'},{cmd:'git clone <url>',desc:'Clone a repository'},{cmd:'git status',desc:'Show working tree status'},{cmd:'git add .',desc:'Stage all changes'},{cmd:'git add <file>',desc:'Stage specific file'},{cmd:'git commit -m "<msg>"',desc:'Commit with message'},{cmd:'git push',desc:'Push to remote'},{cmd:'git pull',desc:'Pull from remote'},{cmd:'git fetch',desc:'Fetch remote changes'},{cmd:'git branch',desc:'List branches'},{cmd:'git branch <name>',desc:'Create branch'},{cmd:'git checkout <branch>',desc:'Switch branch'},{cmd:'git checkout -b <name>',desc:'Create & switch branch'},{cmd:'git merge <branch>',desc:'Merge branch'},{cmd:'git rebase <branch>',desc:'Rebase onto branch'},{cmd:'git log',desc:'View commit history'},{cmd:'git log --oneline',desc:'Compact log view'},{cmd:'git diff',desc:'Show unstaged changes'},{cmd:'git diff --staged',desc:'Show staged changes'},{cmd:'git stash',desc:'Stash changes'},{cmd:'git stash pop',desc:'Apply stashed changes'},{cmd:'git reset HEAD~1',desc:'Undo last commit (keep changes)'},{cmd:'git reset --hard HEAD~1',desc:'Undo last commit (discard)'},{cmd:'git cherry-pick <hash>',desc:'Apply specific commit'},{cmd:'git remote -v',desc:'List remotes'},{cmd:'git tag <name>',desc:'Create tag'}]; this.initElements(); this.bindEvents(); this.render(); }
  initElements() { this.search = document.getElementById('search'); this.list = document.getElementById('cmdList'); }
  bindEvents() { this.search.addEventListener('input', () => this.render()); }
  render() { const q = this.search.value.toLowerCase(); const filtered = this.commands.filter(c => c.cmd.toLowerCase().includes(q) || c.desc.toLowerCase().includes(q)); this.list.innerHTML = filtered.map(c => `<div class="cmd-item" onclick="navigator.clipboard.writeText('${c.cmd.replace(/'/g,"\\'")}')"><div class="cmd-name">${this.escapeHtml(c.cmd)}</div><div class="cmd-desc">${c.desc}</div></div>`).join(''); }
  escapeHtml(s) { return s.replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
}
document.addEventListener('DOMContentLoaded', () => new GitCommands());
