// Swift Snippets - Popup Script
class SwiftSnippets {
  constructor() { this.snippets = [{name:'Hello World',code:'print("Hello, World!")'},{name:'Variables',code:'let name = "Swift"\nvar age = 25\nlet pi: Double = 3.14'},{name:'Function',code:'func greet(name: String) -> String {\n    return "Hello, \\(name)"\n}'},{name:'Struct',code:'struct User {\n    var name: String\n    var age: Int\n    \n    func greet() -> String {\n        return "Hello, \\(name)"\n    }\n}'},{name:'Class',code:'class User {\n    var name: String\n    \n    init(name: String) {\n        self.name = name\n    }\n    \n    func greet() -> String {\n        return "Hello, \\(name)"\n    }\n}'},{name:'Enum',code:'enum Status {\n    case active\n    case inactive\n    case pending(String)\n}'},{name:'Optional',code:'var name: String? = nil\nif let unwrapped = name {\n    print(unwrapped)\n}'},{name:'Guard',code:'guard let name = optionalName else {\n    return\n}\nprint(name)'},{name:'Array',code:'var arr = [1, 2, 3]\narr.append(4)\nfor item in arr {\n    print(item)\n}'},{name:'Dictionary',code:'var dict = ["key": "value"]\ndict["new"] = "item"\nif let val = dict["key"] {\n    print(val)\n}'},{name:'If-Else',code:'if x > 0 {\n    print("positive")\n} else if x < 0 {\n    print("negative")\n} else {\n    print("zero")\n}'},{name:'Switch',code:'switch value {\ncase "a":\n    print("A")\ncase "b":\n    print("B")\ndefault:\n    print("Other")\n}'},{name:'For Loop',code:'for i in 0..<10 {\n    print(i)\n}'},{name:'Closure',code:'let add = { (a: Int, b: Int) -> Int in\n    return a + b\n}'},{name:'Map/Filter',code:'let doubled = nums.map { $0 * 2 }\nlet evens = nums.filter { $0 % 2 == 0 }'},{name:'Try-Catch',code:'do {\n    let result = try somethingThatThrows()\n} catch {\n    print(error)\n}'},{name:'Protocol',code:'protocol Greetable {\n    func greet() -> String\n}'}]; this.initElements(); this.bindEvents(); this.render(); }
  initElements() { this.search = document.getElementById('search'); this.list = document.getElementById('snippetList'); }
  bindEvents() { this.search.addEventListener('input', () => this.render()); }
  render() { const q = this.search.value.toLowerCase(); const filtered = this.snippets.filter(s => s.name.toLowerCase().includes(q) || s.code.toLowerCase().includes(q)); this.list.innerHTML = filtered.map(s => `<div class="snippet-item" onclick="navigator.clipboard.writeText(\`${s.code.replace(/`/g,'\\`').replace(/\\/g,'\\\\')}\`)"><div class="snippet-name">${s.name}</div><div class="snippet-code">${this.escapeHtml(s.code)}</div></div>`).join(''); }
  escapeHtml(s) { return s.replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
}
document.addEventListener('DOMContentLoaded', () => new SwiftSnippets());
