// Emoji Picker - Popup Script
class EmojiPicker {
  constructor() { this.categories = {faces:'😀😃😄😁😆😅🤣😂🙂😊😇🥰😍🤩😘😗😚😋😛😜🤪😝🤑🤗🤭🤫🤔🤐🤨😐😑😶😏😒🙄😬🤥😌😔😪🤤😴😷🤒🤕🤢🤮🤧🥵🥶🥴😵🤯🤠🥳🥸😎🤓🧐😕😟🙁☹️😮😯😲😳🥺😦😧😨😰😥😢😭😱😖😣😞😓😩😫🥱😤😡😠🤬😈👿💀☠️💩🤡👹👺👻👽👾🤖',hands:'👋🤚🖐️✋🖖👌🤌🤏✌️🤞🤟🤘🤙👈👉👆🖕👇☝️👍👎✊👊🤛🤜👏🙌👐🤲🤝🙏✍️💅🤳💪🦾🦿🦵🦶',symbols:'❤️🧡💛💚💙💜🖤🤍🤎💔❣️💕💞💓💗💖💘💝✨⭐🌟💫⚡🔥💥☀️🌈🎉🎊🏆🥇💯✅❌⭕❗❓💬💭🔔🔕📌📍',objects:'⌚📱💻⌨️🖥️🖨️🖱️🖲️💽💾💿📀📷📸📹🎥📞☎️📟📠📺📻🎙️🎚️🎛️🧭⏱️⏲️⏰🔋🔌💡🔦🕯️🧯🛢️💸💵💴💶💷💰💳💎⚖️🧰🔧🔨⚒️🛠️⛏️🔩⚙️🧱⛓️🧲🔫💣🧨🔪🗡️⚔️🛡️🚬⚰️🪦⚱️🏺🔮📿🧿💈⚗️🔭🔬🕳️🩹🩺💊💉🩸🧬🦠🧫🧪🌡️🧹🧺🧻🚽🚰🚿🛁🛀🧼🪥🧴🛎️🔑🗝️🚪🪑🛋️🛏️🛌🧸🖼️🛍️🛒🎁🎈🎏🎀🎊🎉🎎🏮🎐🧧✉️📩📨📧💌📥📤📦🏷️📪📫📬📭📮📯📜📃📄📑🧾📊📈📉🗒️🗓️📆📅🗑️📇🗃️🗳️🗄️📋📁📂🗂️🗞️📰📓📔📒📕📗📘📙📚📖🔖🧷🔗📎🖇️📐📏🧮📌📍✂️🖊️🖋️✒️🖌️🖍️📝✏️🔍🔎🔏🔐🔒🔓',dev:'🔧🔩⚙️🛠️💻🖥️💾📀🔌⚡🔋📶📡🌐🔐🔒🔓🔑🗝️📧📨📩✉️📬📮🏷️📊📈📉📋📌📍✅❌⭕❗❓💬💭🔔🔕🎯🧪🧬🔬💡💰💸🚀⏱️⏲️🔄🔃↩️↪️⤴️⤵️🔀🔁🔂▶️⏸️⏹️⏺️⏭️⏮️🔅🔆📲📳📴'}; this.currentCategory = 'dev'; this.initElements(); this.bindEvents(); this.renderTabs(); this.render(); }
  initElements() { this.search = document.getElementById('search'); this.tabs = document.getElementById('tabs'); this.grid = document.getElementById('emojiGrid'); this.copied = document.getElementById('copied'); }
  bindEvents() { this.search.addEventListener('input', () => this.render()); }
  renderTabs() { const cats = Object.keys(this.categories); this.tabs.innerHTML = cats.map(c => `<button class="tab ${c === this.currentCategory ? 'active' : ''}" data-cat="${c}">${this.categories[c][0]}</button>`).join(''); this.tabs.querySelectorAll('.tab').forEach(btn => btn.addEventListener('click', () => { this.tabs.querySelectorAll('.tab').forEach(b => b.classList.remove('active')); btn.classList.add('active'); this.currentCategory = btn.dataset.cat; this.search.value = ''; this.render(); })); }
  render() { const query = this.search.value.toLowerCase(); let emojis = [...this.categories[this.currentCategory]]; if (query) { emojis = Object.values(this.categories).join('').split('').filter((e, i, a) => a.indexOf(e) === i); } this.grid.innerHTML = emojis.map(e => `<div class="emoji">${e}</div>`).join(''); this.grid.querySelectorAll('.emoji').forEach(el => el.addEventListener('click', () => this.copy(el.textContent))); }
  async copy(emoji) { await navigator.clipboard.writeText(emoji); this.copied.textContent = `Copied: ${emoji}`; setTimeout(() => { this.copied.textContent = ''; }, 1500); }
}
document.addEventListener('DOMContentLoaded', () => new EmojiPicker());
