// JWT Inspector - Popup Script
class JwtInspector {
  constructor() { this.initElements(); this.bindEvents(); }
  initElements() { this.tokenInput = document.getElementById('tokenInput'); this.headerOutput = document.getElementById('headerOutput'); this.payloadOutput = document.getElementById('payloadOutput'); this.signatureOutput = document.getElementById('signatureOutput'); this.status = document.getElementById('status'); this.decodeBtn = document.getElementById('decodeBtn'); }
  bindEvents() { this.decodeBtn.addEventListener('click', () => this.decode()); this.tokenInput.addEventListener('input', () => this.decode()); }
  base64UrlDecode(str) { str = str.replace(/-/g, '+').replace(/_/g, '/'); const pad = str.length % 4; if (pad) str += '='.repeat(4 - pad); return decodeURIComponent(atob(str).split('').map(c => '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2)).join('')); }
  decode() { const token = this.tokenInput.value.trim(); if (!token) { this.headerOutput.textContent = '---'; this.payloadOutput.textContent = '---'; this.signatureOutput.textContent = '---'; this.status.textContent = ''; return; } const parts = token.split('.'); if (parts.length !== 3) { this.showError('Invalid JWT format (expected 3 parts)'); return; } try { const header = JSON.parse(this.base64UrlDecode(parts[0])); const payload = JSON.parse(this.base64UrlDecode(parts[1])); this.headerOutput.textContent = JSON.stringify(header, null, 2); this.payloadOutput.textContent = JSON.stringify(payload, null, 2); this.signatureOutput.textContent = parts[2]; this.checkExpiry(payload); } catch (e) { this.showError('Failed to decode: ' + e.message); } }
  checkExpiry(payload) { if (payload.exp) { const expDate = new Date(payload.exp * 1000); const now = new Date(); if (expDate < now) { this.status.textContent = `⚠ Expired: ${expDate.toLocaleString()}`; this.status.className = 'status expired'; } else { this.status.textContent = `✓ Valid until: ${expDate.toLocaleString()}`; this.status.className = 'status valid'; } } else { this.status.textContent = 'No expiration claim'; this.status.className = 'status'; } }
  showError(msg) { this.headerOutput.textContent = '---'; this.payloadOutput.textContent = '---'; this.signatureOutput.textContent = '---'; this.status.textContent = msg; this.status.className = 'status error'; }
}
document.addEventListener('DOMContentLoaded', () => new JwtInspector());
