// HTML Templates - Popup Script
class HTMLTemplates {
  constructor() { this.templates = [{name:'Basic HTML5',code:'<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>Document</title>\n</head>\n<body>\n  \n</body>\n</html>'},{name:'With CSS/JS',code:'<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>Document</title>\n  <link rel="stylesheet" href="style.css">\n</head>\n<body>\n  \n  <script src="script.js"></script>\n</body>\n</html>'},{name:'Form',code:'<form action="/submit" method="POST">\n  <label for="name">Name:</label>\n  <input type="text" id="name" name="name" required>\n  <label for="email">Email:</label>\n  <input type="email" id="email" name="email" required>\n  <button type="submit">Submit</button>\n</form>'},{name:'Table',code:'<table>\n  <thead>\n    <tr>\n      <th>Header 1</th>\n      <th>Header 2</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td>Data 1</td>\n      <td>Data 2</td>\n    </tr>\n  </tbody>\n</table>'},{name:'Navigation',code:'<nav>\n  <ul>\n    <li><a href="/">Home</a></li>\n    <li><a href="/about">About</a></li>\n    <li><a href="/contact">Contact</a></li>\n  </ul>\n</nav>'},{name:'Card',code:'<div class="card">\n  <img src="image.jpg" alt="Card image">\n  <div class="card-body">\n    <h3>Card Title</h3>\n    <p>Card description text goes here.</p>\n    <a href="#" class="btn">Learn More</a>\n  </div>\n</div>'},{name:'Modal',code:'<div class="modal" id="modal">\n  <div class="modal-content">\n    <span class="close">&times;</span>\n    <h2>Modal Title</h2>\n    <p>Modal content goes here.</p>\n  </div>\n</div>'},{name:'Footer',code:'<footer>\n  <div class="footer-content">\n    <p>&copy; 2024 Company Name</p>\n    <nav>\n      <a href="/privacy">Privacy</a>\n      <a href="/terms">Terms</a>\n    </nav>\n  </div>\n</footer>'},{name:'Meta Tags SEO',code:'<meta name="description" content="Page description">\n<meta name="keywords" content="keyword1, keyword2">\n<meta name="author" content="Author Name">\n<meta property="og:title" content="Page Title">\n<meta property="og:description" content="Description">\n<meta property="og:image" content="image.jpg">'},{name:'Flexbox Container',code:'<div style="display: flex; gap: 1rem; justify-content: center; align-items: center;">\n  <div>Item 1</div>\n  <div>Item 2</div>\n  <div>Item 3</div>\n</div>'},{name:'Grid Container',code:'<div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 1rem;">\n  <div>Item 1</div>\n  <div>Item 2</div>\n  <div>Item 3</div>\n</div>'}]; this.initElements(); this.bindEvents(); this.render(); }
  initElements() { this.search = document.getElementById('search'); this.list = document.getElementById('templateList'); }
  bindEvents() { this.search.addEventListener('input', () => this.render()); }
  render() { const q = this.search.value.toLowerCase(); const filtered = this.templates.filter(t => t.name.toLowerCase().includes(q) || t.code.toLowerCase().includes(q)); this.list.innerHTML = filtered.map(t => `<div class="template-item" onclick="navigator.clipboard.writeText(\`${t.code.replace(/`/g,'\\`')}\`)"><div class="template-name">${t.name}</div><div class="template-code">${this.escapeHtml(t.code)}</div></div>`).join(''); }
  escapeHtml(s) { return s.replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
}
document.addEventListener('DOMContentLoaded', () => new HTMLTemplates());
