// Season Greeting - Popup Script
class SeasonGreeting {
  constructor() { this.greetings = []; this.initElements(); this.bindEvents(); this.loadData(); }
  initElements() { this.seasonEl = document.getElementById('season'); this.recipientEl = document.getElementById('recipient'); this.relationshipEl = document.getElementById('relationship'); this.noteEl = document.getElementById('personalNote'); this.wishesEl = document.getElementById('wishes'); this.copyBtn = document.getElementById('copyGreeting'); this.saveBtn = document.getElementById('saveGreeting'); this.listEl = document.getElementById('greetingList'); }
  bindEvents() { this.copyBtn.addEventListener('click', () => this.copyGreeting()); this.saveBtn.addEventListener('click', () => this.saveGreeting()); }
  async loadData() { const r = await chrome.storage.local.get('seasonGreetings'); if (r.seasonGreetings) this.greetings = r.seasonGreetings; this.render(); }
  async saveData() { await chrome.storage.local.set({ seasonGreetings: this.greetings }); }
  getSeasonLabel(s) { const l = { christmas: 'Merry Christmas', newyear: 'Happy New Year', thanksgiving: 'Happy Thanksgiving', easter: 'Happy Easter', hanukkah: 'Happy Hanukkah', diwali: 'Happy Diwali', lunar: 'Happy Lunar New Year', generic: 'Happy Holidays' }; return l[s] || 'Happy Holidays'; }
  getSeasonWish(s) { const w = { christmas: 'May your holidays be filled with warmth and joy!', newyear: 'Wishing you a prosperous and successful new year!', thanksgiving: 'Grateful for having you in my life!', easter: 'May this season bring you renewed hope and joy!', hanukkah: 'May the Festival of Lights brighten your days!', diwali: 'May the Festival of Lights bring you happiness!', lunar: 'Wishing you prosperity and good fortune!', generic: 'Wishing you joy and happiness this season!' }; return w[s] || w.generic; }
  formatGreeting() { const r = this.recipientEl.value.trim(); const rel = this.relationshipEl.value.trim(); const n = this.noteEl.value.trim(); const w = this.wishesEl.value.trim(); const s = this.seasonEl.value; let g = `Dear ${r || 'Friend'},\n\n${this.getSeasonLabel(s)}!\n\n`; if (rel) g += `As my ${rel}, I wanted to take a moment to reach out during this special time.\n\n`; g += `${this.getSeasonWish(s)}\n\n`; if (n) g += `${n}\n\n`; if (w) g += `${w}\n\n`; g += 'Warm wishes,\n[Your Name]'; return g; }
  async copyGreeting() { await navigator.clipboard.writeText(this.formatGreeting()); const o = this.copyBtn.textContent; this.copyBtn.textContent = 'Copied!'; setTimeout(() => { this.copyBtn.textContent = o; }, 1500); }
  saveGreeting() { const r = this.recipientEl.value.trim(); if (!r) return; this.greetings.unshift({ id: Date.now(), season: this.seasonEl.value, recipient: r, relationship: this.relationshipEl.value.trim(), note: this.noteEl.value.trim(), wishes: this.wishesEl.value.trim(), created: Date.now() }); if (this.greetings.length > 15) this.greetings.pop(); this.saveData(); this.render(); const o = this.saveBtn.textContent; this.saveBtn.textContent = 'Saved!'; setTimeout(() => { this.saveBtn.textContent = o; }, 1500); }
  loadGreeting(id) { const g = this.greetings.find(g => g.id === id); if (g) { this.seasonEl.value = g.season || 'christmas'; this.recipientEl.value = g.recipient || ''; this.relationshipEl.value = g.relationship || ''; this.noteEl.value = g.note || ''; this.wishesEl.value = g.wishes || ''; } }
  deleteGreeting(id) { this.greetings = this.greetings.filter(g => g.id !== id); this.saveData(); this.render(); }
  escapeHtml(t) { const d = document.createElement('div'); d.textContent = t; return d.innerHTML; }
  truncate(t, l = 25) { return (!t || t.length <= l) ? (t || '') : t.substring(0, l) + '...'; }
  render() { if (this.greetings.length === 0) { this.listEl.innerHTML = '<div class="empty-state">No saved greetings</div>'; return; } this.listEl.innerHTML = this.greetings.map(g => `<div class="greeting-item"><div class="greeting-info"><div class="greeting-recipient">${this.escapeHtml(this.truncate(g.recipient))}</div><div class="greeting-season">${this.escapeHtml(g.season)}</div></div><div class="greeting-actions"><button class="load-btn" data-load="${g.id}">Load</button><button class="delete-btn" data-delete="${g.id}">Del</button></div></div>`).join(''); this.listEl.querySelectorAll('[data-load]').forEach(b => b.addEventListener('click', () => this.loadGreeting(parseInt(b.dataset.load)))); this.listEl.querySelectorAll('[data-delete]').forEach(b => b.addEventListener('click', () => this.deleteGreeting(parseInt(b.dataset.delete)))); }
}
document.addEventListener('DOMContentLoaded', () => new SeasonGreeting());
