// JS Minifier - Popup Script
class JsMinifier {
  constructor() { this.initElements(); this.bindEvents(); }
  initElements() { this.inputEl = document.getElementById('input'); this.outputEl = document.getElementById('output'); this.minifyBtn = document.getElementById('minifyBtn'); this.beautifyBtn = document.getElementById('beautifyBtn'); this.copyBtn = document.getElementById('copyBtn'); this.statsEl = document.getElementById('stats'); }
  bindEvents() { this.minifyBtn.addEventListener('click', () => this.minify()); this.beautifyBtn.addEventListener('click', () => this.beautify()); this.copyBtn.addEventListener('click', () => this.copy()); }
  minify() { const js = this.inputEl.value; if (!js.trim()) { this.statsEl.textContent = 'Please enter JavaScript'; return; } const original = js.length; let min = js.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '').replace(/\s+/g, ' ').replace(/\s*([{};:,=+\-*/<>!&|()[\]])\s*/g, '$1').trim(); this.outputEl.value = min; const saved = ((1 - min.length / original) * 100).toFixed(1); this.statsEl.textContent = `Original: ${original} bytes → Minified: ${min.length} bytes (${saved}% saved)`; }
  beautify() { const js = this.inputEl.value; if (!js.trim()) { this.statsEl.textContent = 'Please enter JavaScript'; return; } let indent = 0; let result = ''; let inString = false; let stringChar = ''; for (let i = 0; i < js.length; i++) { const c = js[i]; if ((c === '"' || c === "'") && js[i-1] !== '\\') { if (!inString) { inString = true; stringChar = c; } else if (c === stringChar) { inString = false; } } if (!inString) { if (c === '{') { result += ' {\n' + '  '.repeat(++indent); } else if (c === '}') { result = result.trimEnd(); result += '\n' + '  '.repeat(--indent) + '}\n' + '  '.repeat(indent); } else if (c === ';') { result += ';\n' + '  '.repeat(indent); } else { result += c; } } else { result += c; } } this.outputEl.value = result.replace(/\n\s*\n/g, '\n').trim(); this.statsEl.textContent = 'JavaScript beautified!'; }
  async copy() { if (!this.outputEl.value) { this.statsEl.textContent = 'Nothing to copy'; return; } await navigator.clipboard.writeText(this.outputEl.value); this.statsEl.textContent = 'Copied to clipboard!'; }
}
document.addEventListener('DOMContentLoaded', () => new JsMinifier());
