// HTTP Headers Reference - Popup Script
class HttpHeadersRef {
  constructor() { this.headers = { request: [{name:'Accept',desc:'Media types accepted',example:'Accept: text/html, application/json'},{name:'Authorization',desc:'Authentication credentials',example:'Authorization: Bearer token123'},{name:'Content-Type',desc:'Media type of body',example:'Content-Type: application/json'},{name:'Cookie',desc:'Send cookies to server',example:'Cookie: session=abc123'},{name:'User-Agent',desc:'Client application info',example:'User-Agent: Mozilla/5.0...'},{name:'Cache-Control',desc:'Caching directives',example:'Cache-Control: no-cache'},{name:'Accept-Encoding',desc:'Accepted encodings',example:'Accept-Encoding: gzip, deflate'},{name:'Host',desc:'Target host and port',example:'Host: example.com'},{name:'Origin',desc:'Request origin',example:'Origin: https://example.com'},{name:'Referer',desc:'Previous page URL',example:'Referer: https://google.com'}], response: [{name:'Content-Type',desc:'Media type of response',example:'Content-Type: application/json'},{name:'Set-Cookie',desc:'Set cookie on client',example:'Set-Cookie: id=abc; Path=/'},{name:'Cache-Control',desc:'Caching directives',example:'Cache-Control: max-age=3600'},{name:'Access-Control-Allow-Origin',desc:'CORS allowed origins',example:'Access-Control-Allow-Origin: *'},{name:'Content-Length',desc:'Size of response body',example:'Content-Length: 1234'},{name:'Location',desc:'Redirect URL',example:'Location: /new-page'},{name:'ETag',desc:'Resource version ID',example:'ETag: "abc123"'},{name:'Last-Modified',desc:'Last modification date',example:'Last-Modified: Wed, 01 Jan 2025'},{name:'X-Frame-Options',desc:'Clickjacking protection',example:'X-Frame-Options: DENY'},{name:'Content-Security-Policy',desc:'CSP rules',example:'Content-Security-Policy: default-src self'}] }; this.currentTab = 'request'; this.initElements(); this.bindEvents(); this.render(); }
  initElements() { this.searchInput = document.getElementById('search'); this.headerList = document.getElementById('headerList'); this.tabs = document.querySelectorAll('.tab'); }
  bindEvents() { this.searchInput.addEventListener('input', () => this.render()); this.tabs.forEach(tab => tab.addEventListener('click', () => { this.tabs.forEach(t => t.classList.remove('active')); tab.classList.add('active'); this.currentTab = tab.dataset.tab; this.render(); })); }
  render() { const query = this.searchInput.value.toLowerCase(); const filtered = this.headers[this.currentTab].filter(h => h.name.toLowerCase().includes(query) || h.desc.toLowerCase().includes(query)); this.headerList.innerHTML = filtered.map(h => `<div class="header-item"><div class="header-name">${h.name}</div><div class="header-desc">${h.desc}</div><div class="header-example">${this.escapeHtml(h.example)}</div></div>`).join(''); }
  escapeHtml(str) { const div = document.createElement('div'); div.textContent = str; return div.innerHTML; }
}
document.addEventListener('DOMContentLoaded', () => new HttpHeadersRef());
