// JavaScript Snippets - Popup Script
class JSSnippets {
  constructor() { this.snippets = [{name:'Console Log',code:'console.log("Hello, World!");'},{name:'Variables',code:'const name = "John";\nlet age = 25;\nvar legacy = true;'},{name:'Template Literal',code:'const msg = `Hello, ${name}!`;'},{name:'Arrow Function',code:'const greet = (name) => {\n  return `Hello, ${name}`;\n};'},{name:'Short Arrow',code:'const square = x => x * x;'},{name:'If-Else',code:'if (x > 0) {\n  console.log("positive");\n} else {\n  console.log("not positive");\n}'},{name:'Ternary',code:'const result = x > 0 ? "yes" : "no";'},{name:'For Loop',code:'for (let i = 0; i < 10; i++) {\n  console.log(i);\n}'},{name:'For Of',code:'for (const item of items) {\n  console.log(item);\n}'},{name:'For Each',code:'items.forEach(item => {\n  console.log(item);\n});'},{name:'Map',code:'const doubled = nums.map(n => n * 2);'},{name:'Filter',code:'const evens = nums.filter(n => n % 2 === 0);'},{name:'Reduce',code:'const sum = nums.reduce((a, b) => a + b, 0);'},{name:'Object',code:'const obj = {\n  name: "John",\n  greet() {\n    return `Hi, ${this.name}`;\n  }\n};'},{name:'Destructuring',code:'const { name, age } = person;\nconst [first, second] = array;'},{name:'Spread',code:'const newArr = [...arr1, ...arr2];\nconst newObj = { ...obj1, ...obj2 };'},{name:'Promise',code:'fetch(url)\n  .then(res => res.json())\n  .then(data => console.log(data))\n  .catch(err => console.error(err));'},{name:'Async/Await',code:'async function getData() {\n  try {\n    const res = await fetch(url);\n    const data = await res.json();\n    return data;\n  } catch (err) {\n    console.error(err);\n  }\n}'},{name:'Class',code:'class Person {\n  constructor(name) {\n    this.name = name;\n  }\n  greet() {\n    return `Hi, ${this.name}`;\n  }\n}'}]; this.initElements(); this.bindEvents(); this.render(); }
  initElements() { this.search = document.getElementById('search'); this.list = document.getElementById('snippetList'); }
  bindEvents() { this.search.addEventListener('input', () => this.render()); }
  render() { const q = this.search.value.toLowerCase(); const filtered = this.snippets.filter(s => s.name.toLowerCase().includes(q) || s.code.toLowerCase().includes(q)); this.list.innerHTML = filtered.map(s => `<div class="snippet-item" onclick="navigator.clipboard.writeText(\`${s.code.replace(/`/g,'\\`').replace(/\\/g,'\\\\')}\`)"><div class="snippet-name">${s.name}</div><div class="snippet-code">${this.escapeHtml(s.code)}</div></div>`).join(''); }
  escapeHtml(s) { return s.replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
}
document.addEventListener('DOMContentLoaded', () => new JSSnippets());
