// Query String Parser - Popup Script
class QueryStringParser {
  constructor() { this.params = []; this.initElements(); this.bindEvents(); this.addParamRow(); }
  initElements() { this.urlInput = document.getElementById('urlInput'); this.paramsContainer = document.getElementById('paramsContainer'); this.resultOutput = document.getElementById('resultOutput'); this.parseBtn = document.getElementById('parseBtn'); this.buildBtn = document.getElementById('buildBtn'); this.copyBtn = document.getElementById('copyBtn'); }
  bindEvents() { this.parseBtn.addEventListener('click', () => this.parse()); this.buildBtn.addEventListener('click', () => this.build()); this.copyBtn.addEventListener('click', () => this.copy()); }
  addParamRow(key = '', value = '') { const row = document.createElement('div'); row.className = 'param-row'; row.innerHTML = `<input type="text" class="param-key" placeholder="Key" value="${this.escapeHtml(key)}"><input type="text" class="param-value" placeholder="Value" value="${this.escapeHtml(value)}"><button class="delete-btn">×</button>`; row.querySelector('.delete-btn').addEventListener('click', () => row.remove()); this.paramsContainer.appendChild(row); }
  escapeHtml(str) { const div = document.createElement('div'); div.textContent = str; return div.innerHTML.replace(/"/g, '&quot;'); }
  parse() { let input = this.urlInput.value.trim(); if (!input) return; let queryString = input; if (input.includes('?')) queryString = input.split('?')[1]; if (queryString.includes('#')) queryString = queryString.split('#')[0]; this.paramsContainer.innerHTML = ''; const pairs = queryString.split('&'); for (const pair of pairs) { const [key, value] = pair.split('='); if (key) this.addParamRow(decodeURIComponent(key), decodeURIComponent(value || '')); } if (pairs.length === 0 || !pairs[0]) this.addParamRow(); const parsed = pairs.map(p => { const [k, v] = p.split('='); return `${decodeURIComponent(k)}: ${decodeURIComponent(v || '')}`; }).join('\n'); this.resultOutput.value = parsed; }
  build() { const rows = this.paramsContainer.querySelectorAll('.param-row'); const params = []; rows.forEach(row => { const key = row.querySelector('.param-key').value.trim(); const value = row.querySelector('.param-value').value; if (key) params.push(`${encodeURIComponent(key)}=${encodeURIComponent(value)}`); }); this.resultOutput.value = params.length ? '?' + params.join('&') : ''; }
  async copy() { if (!this.resultOutput.value) return; await navigator.clipboard.writeText(this.resultOutput.value); this.copyBtn.textContent = 'Copied!'; setTimeout(() => { this.copyBtn.textContent = 'Copy'; }, 1500); }
}
document.addEventListener('DOMContentLoaded', () => new QueryStringParser());
