// Escape/Unescape - Popup Script
class EscapeUnescape {
  constructor() { this.initElements(); this.bindEvents(); }
  initElements() { this.input = document.getElementById('input'); this.output = document.getElementById('output'); this.escapeType = document.getElementById('escapeType'); this.escapeBtn = document.getElementById('escapeBtn'); this.unescapeBtn = document.getElementById('unescapeBtn'); this.copyBtn = document.getElementById('copyBtn'); }
  bindEvents() { this.escapeBtn.addEventListener('click', () => this.escape()); this.unescapeBtn.addEventListener('click', () => this.unescape()); this.copyBtn.addEventListener('click', () => this.copy()); }
  escape() { const text = this.input.value; const type = this.escapeType.value; let result = ''; switch(type) { case 'html': result = text.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;'); break; case 'url': result = encodeURIComponent(text); break; case 'json': result = JSON.stringify(text); break; case 'unicode': result = Array.from(text).map(c => c.charCodeAt(0) > 127 ? '\\u' + c.charCodeAt(0).toString(16).padStart(4, '0') : c).join(''); break; case 'backslash': result = text.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/\r/g,'\\r').replace(/\t/g,'\\t').replace(/"/g,'\\"'); break; } this.output.value = result; }
  unescape() { const text = this.input.value; const type = this.escapeType.value; let result = ''; try { switch(type) { case 'html': const doc = new DOMParser().parseFromString(text, 'text/html'); result = doc.documentElement.textContent; break; case 'url': result = decodeURIComponent(text); break; case 'json': result = JSON.parse(text); break; case 'unicode': result = text.replace(/\\u([0-9a-fA-F]{4})/g, (m, hex) => String.fromCharCode(parseInt(hex, 16))); break; case 'backslash': result = text.replace(/\\n/g,'\n').replace(/\\r/g,'\r').replace(/\\t/g,'\t').replace(/\\"/g,'"').replace(/\\\\/g,'\\'); break; } this.output.value = result; } catch (e) { this.output.value = 'Error: ' + e.message; } }
  async copy() { if (!this.output.value) return; await navigator.clipboard.writeText(this.output.value); this.copyBtn.textContent = 'Copied!'; setTimeout(() => { this.copyBtn.textContent = 'Copy Result'; }, 1500); }
}
document.addEventListener('DOMContentLoaded', () => new EscapeUnescape());
