// HTML Entities - Popup Script
class HtmlEntities {
  constructor() { this.entities = [{char:'<',code:'&lt;',name:'Less than'},{char:'>',code:'&gt;',name:'Greater than'},{char:'&',code:'&amp;',name:'Ampersand'},{char:'"',code:'&quot;',name:'Quote'},{char:"'",code:'&#39;',name:'Apostrophe'},{char:' ',code:'&nbsp;',name:'Non-breaking space'},{char:'©',code:'&copy;',name:'Copyright'},{char:'®',code:'&reg;',name:'Registered'},{char:'™',code:'&trade;',name:'Trademark'},{char:'€',code:'&euro;',name:'Euro'},{char:'£',code:'&pound;',name:'Pound'},{char:'¥',code:'&yen;',name:'Yen'},{char:'¢',code:'&cent;',name:'Cent'},{char:'°',code:'&deg;',name:'Degree'},{char:'±',code:'&plusmn;',name:'Plus-minus'},{char:'×',code:'&times;',name:'Multiply'},{char:'÷',code:'&divide;',name:'Divide'},{char:'¼',code:'&frac14;',name:'Quarter'},{char:'½',code:'&frac12;',name:'Half'},{char:'¾',code:'&frac34;',name:'Three quarters'},{char:'←',code:'&larr;',name:'Left arrow'},{char:'→',code:'&rarr;',name:'Right arrow'},{char:'↑',code:'&uarr;',name:'Up arrow'},{char:'↓',code:'&darr;',name:'Down arrow'},{char:'•',code:'&bull;',name:'Bullet'},{char:'…',code:'&hellip;',name:'Ellipsis'},{char:'—',code:'&mdash;',name:'Em dash'},{char:'–',code:'&ndash;',name:'En dash'},{char:'♠',code:'&spades;',name:'Spade'},{char:'♥',code:'&hearts;',name:'Heart'},{char:'♦',code:'&diams;',name:'Diamond'},{char:'♣',code:'&clubs;',name:'Club'}]; this.initElements(); this.bindEvents(); this.render(); }
  initElements() { this.search = document.getElementById('search'); this.list = document.getElementById('entityList'); }
  bindEvents() { this.search.addEventListener('input', () => this.render()); }
  render() { const query = this.search.value.toLowerCase(); const filtered = this.entities.filter(e => e.char.includes(query) || e.code.toLowerCase().includes(query) || e.name.toLowerCase().includes(query)); this.list.innerHTML = filtered.map(e => `<div class="entity-item" onclick="navigator.clipboard.writeText('${e.code}')"><span class="entity-char">${e.char}</span><div class="entity-info"><div class="entity-code">${this.escapeHtml(e.code)}</div><div class="entity-name">${e.name}</div></div></div>`).join(''); }
  escapeHtml(str) { return str.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
}
document.addEventListener('DOMContentLoaded', () => new HtmlEntities());
